sudo: false
notifications:
  email:
  - erik.m.bray+iguananaut@gmail.com
  on_failure: always
language: javascript
branches:
  only:
  - master
install: npm install
script: npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: gh-pages
